In [ ]:
import sys
print(sys.executable)

c:\Users\Aryan Patel\Documents\PST\NumPy\.venv\Scripts\python.exe


In [1]:
import numpy as np
print(np.__version__)


2.4.1


In [ ]:
a = np.array(7)

In [ ]:
a.ndim

0

In [ ]:
b = np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
b.ndim

1

In [ ]:
c = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [ ]:
c.ndim

2

In [ ]:
d = np.array([[[1,2,3]],
              [[4,5,6]],
              [[7,8,9]]])

In [ ]:
d.ndim

3

In [ ]:
e = np.array([[[[1],[2]],[[3],[4]]],
              [[[5],[6]],[[7],[8]]]])

In [ ]:
e.ndim

4

In [ ]:
f = np.array([[[[[1],[2]],[[3],[4]]],[[[7],[8]],[[9],[10]]]],
              [[[[3],[4]],[[5],[6]]],[[[11],[12]],[[13],[14]]]]])

print(f)

[[[[[ 1]
    [ 2]]

   [[ 3]
    [ 4]]]


  [[[ 7]
    [ 8]]

   [[ 9]
    [10]]]]



 [[[[ 3]
    [ 4]]

   [[ 5]
    [ 6]]]


  [[[11]
    [12]]

   [[13]
    [14]]]]]


In [ ]:
f.ndim

5

In [ ]:
g = np.array([1,2,3,4,5,6,7,8,9])
g

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
g.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
g.reshape(2,2,2)  # cannot do this because the size of the array is 9 and this will create a array of 8 elements

In [ ]:
h = np.array([1,2,3,4,5,6,7,8])

In [ ]:
h.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
k = np.zeros([3,4],dtype = int)
k

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
for i in range(k.shape[0]):
    for j in range(k.shape[1]):
        k[i,j] = (i+1)*(j+1)
print(k)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]]


In [ ]:
a1 = [1,2,3]   #list always print with commas
print (a1)

[1, 2, 3]


In [ ]:
a2 = np.array([1,2,3])  # array prints without commas
print(a2)

[1 2 3]


In [ ]:
b = np.array([[1,2,3]])
print(b)

[[1 2 3]]


In [ ]:
b.ndim

2

In [ ]:
l1 = [1,2,3]
l2 = [4,5,6]
l3 = [7,8,9]


In [ ]:
arr = np.array([l1,l2,l3])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a = np.array(range(5))

In [ ]:
print(a)

[0 1 2 3 4]


In [ ]:
a = np.array(range(2,11))
print(a)

TypeError: 'numpy.ndarray' object is not callable

In [ ]:
arrange = np.arange(5)

In [ ]:
print(arrange)

[0 1 2 3 4]


In [ ]:
range = np.array([range(2,10,2)])
print(range)

[[2 4 6 8]]


In [ ]:
arrange = np.arange(2,15,2)
print(arrange)

[ 2  4  6  8 10 12 14]


In [ ]:
k = np.arange(0,60,0.1)
print(k)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9 10.  10.1 10.2 10.3 10.4 10.5 10.6 10.7 10.8 10.9 11.  11.1
 11.2 11.3 11.4 11.5 11.6 11.7 11.8 11.9 12.  12.1 12.2 12.3 12.4 12.5
 12.6 12.7 12.8 12.9 13.  13.1 13.2 13.3 13.4 13.5 13.6 13.7 13.8 13.9
 14.  14.1 14.2 14.3 14.4 14.5 14.6 14.7 14.8 14.9 15.  15.1 15.2 15.3
 15.4 15.5 15.6 15.7 15.8 15.9 16.  16.1 16.2 16.3 16.4 16.5 16.6 16.7
 16.8 16.9 17.  17.1 17.2 17.3 17.4 17.5 17.6 17.7 17.8 17.9 18.  18.1
 18.2 18.3 18.4 18.5 18.6 18.7 18.8 18.9 19.  19.1 19.2 19.3 19.4 19.5
 19.6 

In [ ]:
x = np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [ ]:
y = np.array([[5,6],[9,0]])
print(y)

[[5 6]
 [9 0]]


In [ ]:
y.ndim

2

In [ ]:
print(x+y)

[[ 6  8]
 [12  4]]


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
b = np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
print(np.add(a,b)) # cannot perform this as b is 2 x 2 and not 3 x 3 

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [ ]:
print(x-y)

[[-4 -4]
 [-6  4]]


In [ ]:
print(np.subtract(x,y))

[[-4 -4]
 [-6  4]]


In [ ]:
print(x/y)

[[0.2        0.33333333]
 [0.33333333        inf]]


C:\Users\Aryan Patel\AppData\Local\Temp\ipykernel_5324\1379233019.py:1: RuntimeWarning: divide by zero encountered in divide
  print(x/y)


In [ ]:
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.33333333        inf]]


C:\Users\Aryan Patel\AppData\Local\Temp\ipykernel_5324\2793363925.py:1: RuntimeWarning: divide by zero encountered in divide
  print(np.divide(x,y))


In [ ]:
#Element Wise

print(x*y)

[[ 5 12]
 [27  0]]


In [ ]:
print(np.multiply(x,y))

[[ 5 12]
 [27  0]]


In [ ]:
print(np.dot(x,y))

[[23  6]
 [51 18]]


In [ ]:
print(x.dot(y))

[[23  6]
 [51 18]]


In [ ]:
print(np.cross(x,y))  # cross product only works with vector array which is 1D array

[ -4 -36]


C:\Users\Aryan Patel\AppData\Local\Temp\ipykernel_5324\4011718285.py:1: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  print(np.cross(x,y))


In [ ]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])


In [ ]:
print(np.cross(v1,v2))

[-3  6 -3]


In [ ]:
a4 = np.array([[1,2],[5,6]])

In [ ]:
print(a4)

[[1 2]
 [5 6]]


In [ ]:
y = np.array([[5,6],[9,0]])
print(y)

[[5 6]
 [9 0]]


In [ ]:
print(y.dtype)

int64


In [ ]:
print(np.sum(a4,axis=0)) #axis = 0 means that the sum will happen along rows

[6 8]


In [ ]:
print(np.sum(a4,axis=1))  # axis = 1 means that the sum will happen along columns

[ 3 11]


In [ ]:
print(np.array([True, False]))

[ True False]


In [ ]:
a = np.array([True,False])
print(a.dtype)

bool


In [ ]:
f = np.array([[5.0,6.0],[9,0]])
print(f.dtype)

float64


In [ ]:
d = np.timedelta64(5,"D")  # D means days
print(d)

5 days


In [ ]:
h = np.timedelta64(5,"h")  # H means hours
print(h)

5 hours


In [ ]:
a = np.array(['2026-01-28'], dtype="M8[D]")
print(a.dtype)

datetime64[D]


In [ ]:
print(a)

['2026-01-28']


In [ ]:
str = np.array(['A','BB','CCCC'])

In [ ]:
print(str.dtype)

<U4


In [ ]:
str = str.astype('S4')
str

array([b'A', b'BB', b'CCCC'], dtype='|S4')

In [ ]:
intg = np.array(['1,2,3'])
intg

array(['1,2,3'], dtype='<U5')

In [ ]:
abcd = np.array(['12','23',"34"])
abcd

array(['12', '23', '34'], dtype='<U2')

In [ ]:
abc = np.array(['1','2','3'])
abc

array(['1', '2', '3'], dtype='<U1')

In [ ]:
abc = abc.astype('i')
abc

array([1, 2, 3], dtype=int32)

In [ ]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.sum(arr1)

np.int64(55)

In [ ]:
np.mean(arr1)

np.float64(5.5)

In [ ]:
np.min(arr1)

np.int64(1)

In [ ]:
mat = np.array([[1,2,3],[4,5,6]])

In [ ]:
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.sum(mat,axis=0)

array([5, 7, 9])

In [ ]:
np.sum(mat,axis=1)

array([ 6, 15])

In [ ]:
np.prod(mat,axis=0)

array([ 4, 10, 18])

In [ ]:
np.prod(mat,axis=1)

array([  6, 120])

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
a[7]

np.int64(8)

In [ ]:
a[-2]

np.int64(8)

In [3]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr1[1][1]

np.int64(5)

In [ ]:
arr1[0][1]

np.int64(2)

In [8]:
arr2 = np.array([[[1,2,3],[10,11,12]],
                 [[4,5,6],[13,14,15]],
                 [[7,8,9],[16,17,18]]])

arr2.ndim

3

In [9]:
arr2[1][1][1]

np.int64(14)

In [10]:
arr2[2][0][0]

np.int64(7)

In [12]:
arr2[1][0][1]

np.int64(5)

In [13]:
arr2[0][0][2]

np.int64(3)

In [15]:
arr = np.array([1,2,3,4,5,6])
arr[0:4]

array([1, 2, 3, 4])

In [16]:
arr[2:5]

array([3, 4, 5])

In [20]:
arr12 = np.array([[1,2,3,4,5,6],
                 [7,8,9,10,11,12]])

In [18]:
arr2.ndim

2

In [21]:
arr12[0][1:6]

array([2, 3, 4, 5, 6])

In [22]:
arr12[1][1:4]

array([ 8,  9, 10])

In [26]:
arr13 = np.array([[[1,2,3],[4,5,6]],
                 [[7,8,9],[10,11,12]],
                 [[13,14,15],[16,17,18]]])
arr13.ndim

3

In [29]:
arr13[1][::][-2][1]

np.int64(8)

In [30]:
arr13[1:3][1][0][0]

np.int64(13)

In [31]:
arr13[:3][1][0:2][1][1]

np.int64(11)

In [35]:
arr14 = np.array([[1,2,3,4,5],
                 [5,6,7,8,9]])

In [37]:
arr14[0:2,1:4]

array([[2, 3, 4],
       [6, 7, 8]])