In [6]:
import sys
print(sys.executable)

c:\Users\Aryan Patel\Documents\PST\NumPy\.venv\Scripts\python.exe


In [7]:
import numpy as np
print(np.__version__)


2.4.1


In [13]:
a = np.array(7)

In [16]:
a.ndim

0

In [17]:
b = np.array([1,2,3,4,5,6,7,8,9,10])

In [18]:
b.ndim

1

In [ ]:
c = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [20]:
c.ndim

2

In [ ]:
d = np.array([[[1,2,3]],
              [[4,5,6]],
              [[7,8,9]]])

In [22]:
d.ndim

3

In [ ]:
e = np.array([[[[1],[2]],[[3],[4]]],
              [[[5],[6]],[[7],[8]]]])

In [24]:
e.ndim

4

In [ ]:
f = np.array([[[[[1],[2]],[[3],[4]]],[[[7],[8]],[[9],[10]]]],
              [[[[3],[4]],[[5],[6]]],[[[11],[12]],[[13],[14]]]]])

In [27]:
f.ndim

5

In [29]:
g = np.array([1,2,3,4,5,6,7,8,9])
g

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
g.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
g.reshape(2,2,2)  # cannot do this because the size of the array is 9 and this will create a array of 8 elements

In [33]:
h = np.array([1,2,3,4,5,6,7,8])

In [34]:
h.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [8]:
k = np.zeros([3,4],dtype = int)
k

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
for i in range(k.shape[0]):
    for j in range(k.shape[1]):
        k[i,j] = (i+1)*(j+1)
print(k)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]]
